#pragma once



#define OBSTACLE_CHALLENGE
#define DO_PARK_END

//#define OPEN_CHALLENGE


#define NUMBER_OF_TURNS 3

#define DEBUG_DISPLAY
#define DEBUG_INPUT

#define DOMAIN_SIZE -4, -4, 8
#define DELAY_AFTER_READ_BNO 6
#define DELAY_AFTER_READ_RP2040 5

#define POINT_MATCHING_QUAD_TREE_OPENCL

#define ALGORITHM_ICP

#define MIN_ITERATIONS 1
#define MAX_ITERATIONS 100
#define CONVERGANCE_CONDITION 0.00000000015
#define COST_CONDITION 0.00005


#define BUFFER_SIZE 262144
#define CL_TARGET_OPENCL_VERSION 300
